-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    S: in std_logic;
    R: in std_logic;
    Clk: in std_logic;
    Q: out std_logic;
    Qo: out std_logic);
end main;

architecture Behavioral of main is
  signal Qo_temp: std_logic;
  signal Q_temp: std_logic;
begin
  Q_temp <= NOT ((S AND Clk) OR Qo_temp);
  Qo_temp <= NOT (Q_temp OR (Clk AND R));
  Q <= Q_temp;
  Qo <= Qo_temp;
end Behavioral;
