/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module sr_ff (
  input S,
  input R,
  input Clk,
  output Q,
  output Qo
);
  wire Qo_temp;
  wire Q_temp;
  assign Q_temp = ~ ((S & Clk) | Qo_temp);
  assign Qo_temp = ~ (Q_temp | (Clk & R));
  assign Q = Q_temp;
  assign Qo = Qo_temp;
endmodule
