/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module full_adder (
  input A,
  input B,
  input Ci,
  output S,
  output Co
);
  wire s0;
  assign s0 = (A ^ B);
  assign S = (s0 ^ Ci);
  assign Co = ((s0 & Ci) | (A & B));
endmodule
