-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity fa is
  port (
    A: in std_logic;
    B: in std_logic;
    Ci: in std_logic;
    S: out std_logic;
    Co: out std_logic);
end fa;

architecture Behavioral of fa is
  signal s0: std_logic;
begin
  s0 <= (A XOR B);
  S <= (s0 XOR Ci);
  Co <= ((s0 AND Ci) OR (A AND B));
end Behavioral;
