-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity t_ff is
  port (
    T: in std_logic;
    Clk: in std_logic;
    Q: out std_logic;
    Qo: out std_logic);
end t_ff;

architecture Behavioral of t_ff is
  signal Qo_temp: std_logic;
  signal Q_temp: std_logic;
begin
  Q_temp <= NOT (NOT (Qo_temp AND T AND Clk) AND Qo_temp);
  Qo_temp <= NOT (Q_temp AND NOT (Clk AND T AND Q_temp));
  Q <= Q_temp;
  Qo <= Qo_temp;
end Behavioral;
